### ISSUE TITLE
Couple of questions!

### ISSUE THREAD

**Issue by bobthemighty** [emilybache/Necklace-Refactoring-Kata#3]
I transliterated the python code to Typescript and, while practising the refactoring, I broke one my approval tests. Looking at the code for  I think that a LongChain plain necklace does not fit into the storage. My refactored code placed it on the tree. Is that deliberate or is there a missing condition?

A PendantNecklace with a long chain _does_ have the chain placed on the tree, but any other long necklace is cast aside, and lost beneath the dresser.

Secondly, I'm looking at the code for handling pendant necklaces. Was it a deliberate choice to put diamond pendants on the top shelf, or should they be placed in the safe with the other diamonds?

Edit: easily the weirdest github issue I've ever opened.

**Comment by emilybache** [comment]
Hi Bob,

I’m really pleased to hear from you about this exercise. I’m still working on it, and this kind of feedback is really valuable. I’d like to invite you to the Samman Society Slack. I was hoping we could have this kind of discussion there, with other coaches too. (You’re not the only person working on this kata!)

https://join.slack.com/t/sammansociety/shared_invite/zt-17eg41aqf-c_76apN8UW_MjyWoh19c2Q <https://join.slack.com/t/sammansociety/shared_invite/zt-17eg41aqf-c_76apN8UW_MjyWoh19c2Q>

You were quite right, LongChain plain necklaces should not end up on the floor! I have modified the logic a little in my latest version of this code, so that doesn’t happen.

I think you’re right that diamond pendants should also end up in the safe. I’m thinking to make that a new feature request that will be easier once the code is refactored.

Thankyou so much for getting in touch, and I look forward to a pull request for typescript when you’re ready :-)

This kata is still a work in progress, I hope you don’t get discouraged now I’m changing it a little.

Regards,
Emily

**Comment by bobthemighty** [comment]
I am rarely discouraged! I'll update my Typescript version and have another go

**Comment by emilybache** [comment]
Fixed in an update!
